import { ComponentMeta, ComponentStory } from '@storybook/react';
import AppStore from '../..//assets/appStore';
import Instagram from '../..//assets/insta';
import LinkedIn from '../..//assets/linkedIn';
import PlayStore from '../../assets/plastore';
import { Performance } from '../performance';
import Footer from './footer';

export default {
  title: 'Components/Footer',
  component: Footer,
} as ComponentMeta<typeof Footer>;

const Template: ComponentStory<typeof Footer> = (args) => <Footer {...args} />;

export const Primary = Template.bind({});
Primary.args = {
  headingStyle: {},
  subTitleStyle: {},
  rootStyles: {},
  componentStyle: {},
  logoContainerStyle: {},
  companyLogoBlockStyle: {},
  subcriptionBlockStyle: {},
  bottomTextBlockStyle: {},
  bottomTexStyle: {},
  hoverHeading: {},
  hoverSubTitle: {},
  footerData: [
    {
      order: 1,
      heading: {
        id: 1,
        title: 'Links',
        icon: '',
        iconDirection: '',
        styles: '',
        onClick: () => {},
      },
      component: "",
      subTitle: [
        {
          subValue: 'Home',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          nested: {
            heading: {
              id: 2,
              title: 'Henry',
              styles: '',
              onClick: () => {},
            },
            subTitle: [
              {
                subValue: 'SUbText',
                icon: '',
                iconDirection: '',
                styles: '',
                onClick: () => {},
                link: '',
              },
              {
                subValue: 'HElo',
                icon: '',
                iconDirection: '',
                styles: '',
                onClick: () => {},
                link: '',
              },
              {
                subValue: 'Create',
                icon: '',
                iconDirection: '',
                styles: '',
                onClick: () => {},
                link: '',
              },
            ],
          },
        },
        {
          subValue: 'About us',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
        },
        {
          subValue: 'Solution',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
        },
        {
          subValue: 'Modules',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 3,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Products',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 4,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Pricing',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 5,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'FAQ',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 6,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Blogs',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 7,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Resource',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 8,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Conduct us',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 9,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
      ],
    },
    {
      order: 2,
      heading: {
        id: 10,
        title: 'Solution',
        icon: '',
        iconDirection: '',
        styles: '',
      },
      subTitle: [
        {
          subValue: 'Home',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 11,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'About us',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 12,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Solution',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 3,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Modules',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 14,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Products',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 15,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Pricing',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 16,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'FAQ',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 17,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
      ],
      component: ""
    },
    {
      order: 3,
      heading: {
        id: 18,
        title: 'Apps',
        styles: '',
        icon: '',
        iconDirection: '',
      },
      subTitle: [
        {
          subValue: 'Home',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: { id: 19, title: '', styles: '' },
        },
        {
          subValue: 'About us',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 20,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Solution',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 21,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Modules',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 22,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Products',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 23,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Pricing',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 24,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'FAQ',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 25,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
      ],
      component: ""
    },
    {
      order: 4,
      heading: {
        id: 26,
        title: 'Property Automate & Partners',
        styles: '',
        icon: '',
        iconDirection: '',
      },
      subTitle: [
        {
          subValue: 'Dynamic Netsoft RealEstatePro',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 27,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Listings.GOTO',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 28,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Residential.GOTO',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 29,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'MCommercial.GOTO',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 31,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Marketplace.GOTO',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 30,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'Pricing',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 32,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
        {
          subValue: 'FAQ',
          icon: '',
          iconDirection: '',
          styles: '',
          onClick: () => {},
          link: '',
          heading: {
            id: 33,
            title: 'Links',
            styles: '',
            onClick: () => {},
          },
        },
      ],
      component: ""
    },
  ],

  footerLogo: [
    {
      companyLogo: {
        label: 'Crayond',
        logo: <Performance />,
      },
      subscribes: [
        { icon: <PlayStore /> },
        { icon: <AppStore /> },
        { icon: <AppStore /> },
        { icon: <LinkedIn /> },
        { icon: <Instagram /> },
        { icon: <LinkedIn /> },
        { icon: <Instagram /> },
      ],
      termsOfPolicy: [
        { label: 'Terms of Service' },
        { label: 'Privacy Policy' },
        { label: ' Policy' },
        { label: 'Privacy ' },
      ],
      copy: [
        { label: 'Crayond ©' },
        { label: 'All s reserved' },
        { label: 'creating Copy' },
      ],
    },
  ],
};
